// SUPPLIES

export const GET_SUPPLIES_START = "GET_SUPPLIES_START";
export const GET_SUPPLIES_SUCCESS = "GET_SUPPLIES_SUCCESS";
export const GET_SUPPLIES_ERROR = "GET_SUPPLIES_ERROR";

// SUPPLIERS

export const GET_SUPPLIERS_START = "GET_SUPPLIERS_START";
export const GET_SUPPLIERS_SUCCESS = "GET_SUPPLIERS_SUCCESS";
export const GET_SUPPLIERS_ERROR = "GET_SUPPLIERS_ERROR";
