// SUPPLIES

// GET
export const GET_SUPPLIES_START = "GET_SUPPLIES_START";
export const GET_SUPPLIES_SUCCESS = "GET_SUPPLIES_SUCCESS";
export const GET_SUPPLIES_ERROR = "GET_SUPPLIES_ERROR";
//POST
export const ADD_SUPPLY_START = "ADD_SUPPLY_START";
export const ADD_SUPPLY_SUCCESS = "ADD_SUPPLY_SUCCESS";
export const ADD_SUPPLY_ERROR = "ADD_SUPPLY_ERROR";
// PUT (PATCH)
export const UPDATE_SUPPLY_START = "UPDATE_SUPPLY_START";
export const UPDATE_SUPPLY_SUCCESS = "UPDATE_SUPPLY_SUCCESS";
export const UPDATE_SUPPLY_ERROR = "UPDATE_SUPPLY_ERROR";
// DELETE
export const DELETE_SUPPLY_START = "DELETE_SUPPLY_START";
export const DELETE_SUPPLY_SUCCESS = "DELETE_SUPPLY_SUCCESS";
export const DELETE_SUPPLY_ERROR = "DELETE_SUPPLY_ERROR";

// SUPPLIERS

// GET
export const GET_SUPPLIERS_START = "GET_SUPPLIERS_START";
export const GET_SUPPLIERS_SUCCESS = "GET_SUPPLIERS_SUCCESS";
export const GET_SUPPLIERS_ERROR = "GET_SUPPLIERS_ERROR";
// POST
export const ADD_SUPPLIER_START = "ADD_SUPPLIER_START";
export const ADD_SUPPLIER_SUCCESS = "ADD_SUPPLIER_SUCCESS";
export const ADD_SUPPLIER_ERROR = "ADD_SUPPLIER_ERROR";
// PUT (PATCH)
export const UPDATE_SUPPLIER_START = "UPDATE_SUPPLIER_START";
export const UPDATE_SUPPLIER_SUCCESS = "UPDATE_SUPPLIER_SUCCESS";
export const UPDATE_SUPPLIER_ERROR = "UPDATE_SUPPLIER_ERROR";
// DELETE
export const DELETE_SUPPLIER_START = "DELETE_SUPPLIER_START";
export const DELETE_SUPPLIER_SUCCESS = "DELETE_SUPPLIER_SUCCESS";
export const DELETE_SUPPLIER_ERROR = "DELETE_SUPPLIER_ERROR";

// AUTH
export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_ERROR = "AUTH_ERROR";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

// export const SET_MAIN_USER_TOKEN_START = "SET_MAIN_USER_TOKEN_START";
// export const SET_MAIN_USER_TOKEN_SUCCESS = "SET_MAIN_USER_TOKEN_SUCCESS";

// PURCHASES

// GET

export const GET_PURCHASES_START = "GET_PURCHASES_START";
export const GET_PURCHASES_SUCCESS = "GET_PURCHASES_SUCCESS";
export const GET_PURCHASES_ERROR = "GET_PURCHASES_SUCCESS";

// POST

export const ADD_PURCHASE_START = "ADD_PURCHASE_START";
export const ADD_PURCHASE_SUCCESS = "ADD_PURCHASE_SUCCESS";
export const ADD_PURCHASE_ERROR = "ADD_PURCHASE_ERROR";

// GET DETAILS

export const GET_PURCHASE_DETAILS_START = "GET_PURCHASE_DETAILS_START";
export const GET_PURCHASE_DETAILS_SUCCESS = "GET_PURCHASE_DETAILS_SUCCESS";
export const GET_PURCHASE_DETAILS_ERROR = "GET_PURCHASE_DETAILS_ERROR";
export const CLEAR_PURCHASE_DETAILS = "CLEAR_PURCHASE_DETAILS";
