// SUPPLIES

// GET
export const GET_SUPPLIES_START = "GET_SUPPLIES_START";
export const GET_SUPPLIES_SUCCESS = "GET_SUPPLIES_SUCCESS";
export const GET_SUPPLIES_ERROR = "GET_SUPPLIES_ERROR";
//POST
export const ADD_SUPPLY_START = "ADD_SUPPLY_START";
export const ADD_SUPPLY_SUCCESS = "ADD_SUPPLY_SUCCESS";
export const ADD_SUPPLY_ERROR = "ADD_SUPPLY_ERROR";
// PUT (PATCH)
export const UPDATE_SUPPLY_START = "UPDATE_SUPPLY_START";
export const UPDATE_SUPPLY_SUCCESS = "UPDATE_SUPPLY_SUCCESS";
export const UPDATE_SUPPLY_ERROR = "UPDATE_SUPPLY_ERROR";
// DELETE
export const DELETE_SUPPLY_START = "DELETE_SUPPLY_START";
export const DELETE_SUPPLY_SUCCESS = "DELETE_SUPPLY_SUCCESS";
export const DELETE_SUPPLY_ERROR = "DELETE_SUPPLY_ERROR";

// SUPPLIERS

// GET
export const GET_SUPPLIERS_START = "GET_SUPPLIERS_START";
export const GET_SUPPLIERS_SUCCESS = "GET_SUPPLIERS_SUCCESS";
export const GET_SUPPLIERS_ERROR = "GET_SUPPLIERS_ERROR";
// POST
export const ADD_SUPPLIER_START = "ADD_SUPPLIER_START";
export const ADD_SUPPLIER_SUCCESS = "ADD_SUPPLIER_SUCCESS";
export const ADD_SUPPLIER_ERROR = "ADD_SUPPLIER_ERROR";
// PUT (PATCH)
export const UPDATE_SUPPLIER_START = "UPDATE_SUPPLIER_START";
export const UPDATE_SUPPLIER_SUCCESS = "UPDATE_SUPPLIER_SUCCESS";
export const UPDATE_SUPPLIER_ERROR = "UPDATE_SUPPLIER_ERROR";
// DELETE
export const DELETE_SUPPLIER_START = "DELETE_SUPPLIER_START";
export const DELETE_SUPPLIER_SUCCESS = "DELETE_SUPPLIER_SUCCESS";
export const DELETE_SUPPLIER_ERROR = "DELETE_SUPPLIER_ERROR";

// AUTH
export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_ERROR = "AUTH_ERROR";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

// export const SET_MAIN_USER_TOKEN_START = "SET_MAIN_USER_TOKEN_START";
// export const SET_MAIN_USER_TOKEN_SUCCESS = "SET_MAIN_USER_TOKEN_SUCCESS";

// PURCHASES

// GET

export const GET_PURCHASES_START = "GET_PURCHASES_START";
export const GET_PURCHASES_SUCCESS = "GET_PURCHASES_SUCCESS";
export const GET_PURCHASES_ERROR = "GET_PURCHASES_ERROR";

// POST

export const ADD_PURCHASE_START = "ADD_PURCHASE_START";
export const ADD_PURCHASE_SUCCESS = "ADD_PURCHASE_SUCCESS";
export const ADD_PURCHASE_ERROR = "ADD_PURCHASE_ERROR";

// CATEGORIES

// GET

export const GET_CATEGORIES_START = "GET_CATEGORIES_START";
export const GET_CATEGORIES_SUCCESS = "GET_CATEGORIES_SUCCESS";
export const GET_CATEGORIES_ERROR = "GET_CATEGORIES_ERROR";

// POST

export const ADD_CATEGORY_START = "ADD_CATEGORY_START";
export const ADD_CATEGORY_SUCCESS = "ADD_CATEGORY_SUCCESS";
export const ADD_CATEGORY_ERROR = "ADD_CATEGORY_ERROR";

// PATCH

export const UPDATE_CATEGORY_START = "UPDATE_CATEGORY_START";
export const UPDATE_CATEGORY_SUCCESS = "UPDATE_CATEGORY_SUCCESS";
export const UPDATE_CATEGORY_ERROR = "UPDATE_CATEGORY_ERROR";

// DELETE

export const DELETE_CATEGORY_START = "DELETE_CATEGORY_START";
export const DELETE_CATEGORY_SUCCESS = "DELETE_CATEGORY_SUCCESS";
export const DELETE_CATEGORY_ERROR = "DELETE_CATEGORY_ERROR";

// DISHES

// GET

export const GET_DISHES_START = "GET_DISHES_START";
export const GET_DISHES_SUCCESS = "GET_DISHES_SUCCESS";
export const GET_DISHES_ERROR = "GET_DISHES_ERROR";

// POST

export const ADD_DISH_START = "ADD_DISH_START";
export const ADD_DISH_SUCCESS = "ADD_DISH_SUCCESS";
export const ADD_DISH_ERROR = "ADD_DISH_ERROR";

// PATCH

export const UPDATE_DISH_START = "UPDATE_DISH_START";
export const UPDATE_DISH_SUCCESS = "UPDATE_DISH_SUCCESS";
export const UPDATE_DISH_ERROR = "UPDATE_DISH_ERROR";

// DELETE

export const DELETE_DISH_START = "DELETE_DISH_START";
export const DELETE_DISH_SUCCESS = "DELETE_DISH_SUCCESS";
export const DELETE_DISH_ERROR = "DELETE_DISH_ERROR";

// COMBOS

// GET

export const GET_COMBOS_START = "GET_COMBOS_START";
export const GET_COMBOS_SUCCESS = "GET_COMBOS_SUCCESS";
export const GET_COMBOS_ERROR = "GET_COMBOS_ERROR";

// POST

export const ADD_COMBO_START = "ADD_COMBO_START";
export const ADD_COMBO_SUCCESS = "ADD_COMBO_SUCCESS";
export const ADD_COMBO_ERROR = "ADD_COMBO_ERROR";

// PATCH

export const UPDATE_COMBO_START = "UPDATE_COMBO_START";
export const UPDATE_COMBO_SUCCESS = "UPDATE_COMBO_SUCCESS";
export const UPDATE_COMBO_ERROR = "UPDATE_COMBO_ERROR";

// DELETE

export const DELETE_COMBO_START = "DELETE_COMBO_START";
export const DELETE_COMBO_SUCCESS = "DELETE_COMBO_SUCCESS";
export const DELETE_COMBO_ERROR = "DELETE_COMBO_ERROR";
